sudo: required

services:
  - docker

before_script:
  - cd tests
  - docker build -t j-ulrich/http-status-codes -f Dockerfile ..

script:
  - > 
    docker run j-ulrich/http-status-codes /bin/bash -c "
    g++ --version
    && qmake --version
    && cd tests
    && mkdir _build
    && cd _build
    && cmake -DCMAKE_BUILD_TYPE=Release ..
    && make all
    && ctest --ouput-on-failure
    "